### ISSUE TITLE
error

### ISSUE THREAD

**Issue by adilhyz** [KatowProject/komikato#1]
/komikato/controllers/komikindo/general.js:153
                    thumb: $(m).find('.limit > img').attr('src')?.split('?')[0],
                                                                 ^

SyntaxError: Unexpected token '.'

**Comment by KatowProject** [comment]
pakai nodejs versi berapa?

**Comment by adhilhyz** [comment]
adhyl@h4yyz:~$ node
Welcome to Node.js v12.22.10.
Type ".help" for more information.

**Comment by KatowProject** [comment]
update dulu ke versi v14.x.x
