### ISSUE TITLE
Error memutar video 

### ISSUE THREAD

**Issue by adilhyz** [KatowProject/komikato#2]

**Comment by KatowProject** [comment]
![](https://cdn.discordapp.com/attachments/932997960923480099/966286027469770843/unknown.png)

fixed, jangan lupa pull buat update

**Comment by adilhyz** [comment]
> ![](https://camo.githubusercontent.com/20289e1ac65568ca81a06c79e70db7b591f46c5227ffdc4436b85cf72cf7077c/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3933323939373936303932333438303039392f3936363238363032373436393737303834332f756e6b6e6f776e2e706e67)
> 
> fixed, jangan lupa pull buat update

pull request emang guna nya untuk apa bang?, maaf masih awam 🙏

**Comment by KatowProject** [comment]
> > ![](https://camo.githubusercontent.com/20289e1ac65568ca81a06c79e70db7b591f46c5227ffdc4436b85cf72cf7077c/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3933323939373936303932333438303039392f3936363238363032373436393737303834332f756e6b6e6f776e2e706e67)
> > fixed, jangan lupa pull buat update
> 
> pull request emang guna nya untuk apa bang?, maaf masih awam 🙏

bukan pull request, ke folder repo yang udah kamu clone, kemudian buka terminal di situ, terus ketik **git pull**

**Comment by amsionglau** [comment]
Ada kontak yang bisa di hubungi mas?

**Comment by KatowProject** [comment]
> Ada kontak yang bisa di hubungi mas?

bisa ke discord saya ManLord#3143

**Comment by amsionglau** [comment]
> > Ada kontak yang bisa di hubungi mas?
> 
> bisa ke discord saya ManLord#3143

Accept mas
